apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: limited-services
spec:
  hostnames:
    - "kind.418.local"
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-system
      sectionName: web
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /whoami
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: whoami
          namespace: limited-services
          port: 80