apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: limited-services
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik-system
      sectionName: web
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: whoami
          namespace: limited-services
          port: 80